// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ozcrrfbmmnqbhpjwwemb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im96Y3JyZmJtbW5xYmhwand3ZW1iIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjI0MzI0NTEsImV4cCI6MjA3ODAwODQ1MX0.szGmsJtd3HHg6ZfxEHPLzNh5Uv0zt-OLtfQIKJP52D0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});